version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin123
    volumes:
      - C:\Users\Pedro\OneDrive\Documentos\Backend\postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pedromakengo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '8081:80'
    depends_on:
      - db
